
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-17T15:46:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd2224538aac5aeb6c0dfa145af3886f192f3537",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
